services:
  feed-proxy:
    image: ghcr.io/vicchi/feed-proxy:latest
    networks:
      - vicchi-backend
    expose:
      - 80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.vicchi-org.rule=Host(`${SITE_HOST:?Site host not defined}`)
      - traefik.http.routers.vicchi-org.entrypoints=websecure
      - traefik.http.routers.vicchi-org.tls.certresolver=reverse-proxy-http
      - traefik.http.routers.vicchi-org.tls.options=proxy-default@file
      - traefik.http.routers.vicchi-org.middlewares=secHeaders@file
    volumes:
      - ./.env:/service/.env
      - ./gunicorn.conf.py:/service/gunicorn.conf.py
      - ./data-stores:/service/data-stores
  
networks:
    vicchi-backend:
      external: true
